server:
  port: 8081
spring:
    datasource:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://127.0.0.1:3306/local_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
            username: root
            password: 123456
            type: com.alibaba.druid.pool.DruidDataSource
            initialSize: 5
            minIdle: 5
            maxActive: 50
            maxWait: 1000
            filters: stat,wall,log4j